-- =============================================================================
-- Crear tabla obra_conceptos desde cero (SIN FKs para poder importar el CSV)
-- Después de importar, ejecuta: aplicar_fk_obra_conceptos.sql
-- =============================================================================

-- Si la tabla ya existe y quieres recrearla, descomenta la línea siguiente:
-- DROP TABLE IF EXISTS public.obra_conceptos CASCADE;

CREATE TABLE public.obra_conceptos (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idobra                 integer NOT NULL,
  id_concepto            integer NOT NULL,
  cantidad               numeric(15,2) NOT NULL,
  medicion               character varying(100),
  costo                  numeric(15,2) NOT NULL,
  total                  numeric(15,2) NOT NULL,
  observaciones          text,
  fecha_creacion         timestamp without time zone DEFAULT now(),
  id_usuario_creacion    integer NOT NULL DEFAULT 1,
  fecha_modificacion     timestamp without time zone,
  id_usuario_modificacion integer,
  estado                 integer DEFAULT 1
  -- FKs se agregan después de importar con aplicar_fk_obra_conceptos.sql
);

-- Índices útiles para consultas y reportes
CREATE INDEX idx_obra_conceptos_idobra ON public.obra_conceptos (idobra);
CREATE INDEX idx_obra_conceptos_id_concepto ON public.obra_conceptos (id_concepto);
CREATE INDEX idx_obra_conceptos_obra_concepto ON public.obra_conceptos (idobra, id_concepto);

COMMENT ON TABLE public.obra_conceptos IS 'Conceptos por obra; idobra -> op_obras.idobra, id_concepto -> conceptos.id';
